name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the main branch.
  push:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can
      # access it.
      - uses: actions/checkout@v2

      - name: Run Python code formatting with Black
        uses: lgeiger/black-action@v1.0.1
        with:
          args: "."

      - name: Run front-end code formatting with Prettier
        uses: creyD/prettier_action@v3.3
        with:
          commit_message: Format code with Black and Prettier
          prettier_options: --write {**/*,*}.{js,ts,jsx,tsx,html,css}
